### ISSUE TITLE
Documentation not found

### ISSUE THREAD

**Issue by OceanWolf** [SimonSapin/cssselect2#4]
The readme links to http://pythonhosted.org/cssselect2/ for the documentation, but it gives a 404 Not Found error.

**Comment by SimonSapin** [comment]
Fixed, thanks!

**Comment by OceanWolf** [comment]
A pleasure, but it still doesn't work for me.  The new link just redirects to the old one...

I find documentation for ``cssselect`` but not ``cssselect2``... does it work for you?

**Comment by SimonSapin** [comment]
Ah, yes. I pushed that "fix" in a hurry and should have checked. The docs link is a 404 because there aren’t any docs. I’ve removed the link.

I wouldn’t recommend using cssselect2 in its current state. It’s really at the "experimenting" stage. I kinda got stuck at https://github.com/SimonSapin/cssselect2/issues/1 and then moved on to other things. If you just want to *use* a selector matching thing today, practically I’d recommend cssselect (not 2) despite its flaws. If you’d want to *develop* one, cssselect2 could

**Comment by OceanWolf** [comment]
You should also remove the link on the pypi page as well (the one linked to from the readme).  and ahh, okay, I will take a look at that issue tomorrow or something.

At the moment I just wanted to do some research of the software out there for css parsing, figuring out which package does what etcetera and if it will suit our needs, and this package had a nice example that covers ``tinycss2`` as well.

I develop for matplotlib, an open-source python graph plotting programme, and a project we have had a project on the back burner for a while about introducing CSS-like style sheets which would greatly improve the usability and flexibility of the software.  If you want to get a feel for what we had in mind you can take a look at https://github.com/matplotlib/matplotlib/blob/master/doc/devel/MEP/MEP26.rst

I shy away from ``tinycss`` and ``cssselect`` as they do too much, not generic enough for custom element and property names, etcetera.

But yes, right now just play-time, and seeing if we can save ourselves some code by using an external library :).

**Comment by SimonSapin** [comment]
I’ve rewritten the README to explain that this is not maintained: https://github.com/SimonSapin/cssselect2/blob/13895eed8b/README.rst
